sudo: required

language: node_js
node_js:
  - "lts/*"

services:
  - docker

before_install:
  - docker pull artioml/hello-world
  - docker run -dit -p 80:8080 artioml/hello-world
  - docker ps -a

script:
  - curl -s http://127.0.0.1/ | grep 'hello, world'

notifications:
  slack:
    secure: "TMaVLYRzpDE2f0ajpga2OKYq16xtG93kB9gCjX/yGX2zo9lEymP18OXDLIvaux+lLkfTCGFu1jk0UzhkcvIVi6nArpH0/0r4VzHv+Mckg9kCQVUcZpkCUGvG7KWanRJ4zXcbUM7E0/2p1LinpwAnUSg5o8Bgo7zZi1HaX3C4o81BqXDsTb8TpyLpTIuszvBR/NNij5YrurbrqhPE3igDwLINjN0F5o9c/aEkWSKdbsdtpv+7JDyWQ3XaLL6buJFYFXtB7R7vz4af/8v4jK9QTdpwQCjKiH/ee+p/T/0R9C6CeCcXvZsAX+6ZdVmoLUvQI+sKiyqilwZgM5z54xFcb62ZTvioLX7+CZN9y2nH75LqBHgO5CIpI7YMKySiQ3VnD92JgtQxu8Ah6mhG9pRT91GoM/GmBHOtpWhghoPcpy23z18ho6PTjKfQqkegdR7rG9U933rdNNss8Yd0t9pPrHM+8LrgzVm0SVxt34ZFmr6z3nTDZFSiYFIvJZMog40vd5pxCQGXPcAXk/h39DQDEEWd9UW53gyEfm714VTxiphejUvvMfxCEAuu7wWIhIy3Gw9xgMTPpkBZ081UGvWwji5kXhJfGy1D6z1JqADRgoQk+SepU73QR0d5HXtFoEdAd99/CBT2djjSAISQ4xMu+RDBEnjsCE/qHrL4FuwIXDg="
